dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  http: ^0.13.6
  path_provider: ^2.0.15
  image_picker: ^1.0.7
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  video_player: ^2.7.0
  intl: ^0.18.1
  timezone: ^0.9.2
  lottie: ^2.7.0
  web_socket_channel: ^2.4.0
  google_fonts: ^4.0.4
  fl_chart: ^0.66.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  google_places_flutter: ^2.0.6
  url_launcher: ^6.2.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  math_expressions: ^2.6.0


flutter:
  assets:
    - assets/questions.json
    - assets/cloudy.json
    - assets/rainy.json
    - assets/sunny.json
    - assets/snowy.json
